#!/bin/csh

source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

f77 -c main.f
f77 -c annual.f
f77 -c loadinfo.f

f77 -o ../../../../bin/Rannual.exe annual.o loadinfo.o main.o $dsnlib $lib1 $lib2 $lib3 ../postriverlib.a $usrlib

rm *.o

