#!/bin/csh

source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

f77 -c main.f
f77 -c smrating.f
f77 -c obrating.f
f77 -c caloadinfo.f
f77 -c gethours.f
f77 -c seperation.f
f77 -c transform.f

f77 -o ../../../../bin/TSSRating.exe main.o caloadinfo.o seperation.o gethours.o smrating.o obrating.o transform.o $dsnlib $lib1 $lib2 $lib3 ../postriverlib.a $usrlib ../part/part_sub.o

rm *.o
