#!/bin/csh

  set usrdir = ../../../lib
  set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

  f77 -c main.f
  f77 -c readcontrol_vartypes.f
  f77 -c plt2cal.f

  f77 -o ../../../../bin/pltgen.exe main.o readcontrol_vartypes.o plt2cal.o $usrlib

  rm *.o

