#!/bin/csh

source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a

f77 -c checkriver.f
f77 -c getl2r.f
f77 -c getrflags.f
f77 -c getevap.f
f77 -c getupstream.f
f77 -c getallupstream.f
f77 -c getconseg.f
f77 -c getlutype.f
f77 -c readseglist.f
f77 -c getrsegs.f
f77 -c getBMPcons.f
f77 -c getvarfac.f

f77 -c getconfluence.f

ar rv ../get_lib.a checkriver.o getl2r.o getrflags.o getevap.o getupstream.o getallupstream.o getconseg.o getlutype.o readseglist.o getrsegs.o getBMPcons.o getvarfac.o

f77 -o ../../../bin/getconfluence.exe getconfluence.o ../../lib/dsn/dsn_utils.o $lib1 $lib2 $lib3 ../../lib/get_lib.a ../../lib/util_lib.a

rm *.o
