#!/bin/csh
source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o

f77 -c main.f
f77 -c loadinfo.f
f77 -c masslink.f
f77 -c readcontrol_tmsce.f
f77 -c writeEOannual.f
f77 -c writeEOaveann.f
f77 -c writeEOdaily.f
f77 -c writeEOmonthly.f

f77 -o ../../../bin/etm_and_postproc.exe main.o loadinfo.o masslink.o readcontrol_tmsce.o writeEOannual.o writeEOaveann.o writeEOdaily.o writeEOmonthly.o $usrlib $dsnlib $lib1 $lib2 $lib3

rm *.o

