#!/bin/csh

source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

f77 -c main.f
f77 -c readcontrol_vartypes.f
f77 -c plt2cal.f
f77 -c loadavann.f
f77 -c loadinfo.f
f77 -c gethours.f

f77 -o ../../../../bin/Rpltgen.exe loadinfo.o main.o gethours.o loadavann.o readcontrol_vartypes.o plt2cal.o $dsnlib $lib1 $lib2 $lib3 ../../river/postriverlib.a $usrlib ../../river/part/part_sub.o

  rm *.o

